### Register User
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "name": "fatima",
  "email": "francisssssss",
  "password": "123456789"
}

### Verify Email
GET http://localhost:3000/api/user/verify-email/<token>

### Login User
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "isabella.bertucci17@gmail.com",
  "password": "123456789"
}

### Get User Data
GET http://localhost:3000/api/user/me
Authorization: Bearer <your_jwt_token_here>

### EDIT LOGGED USER
PATCH http://localhost:3000/api/user/me
Authorization: Bearer <your_jwt_token_here>
Content-Type: application/json

{
  "name": "new_name_yey",
}

### DELETE LOGGED USER
DELETE http://localhost:3000/api/user/me
Authorization: Bearer <your_jwt_token_here>


### ADMIN 


### GET ALL USERS 
GET http://localhost:3000/api/user/
Authorization: Bearer <your_admin_jwt_token>


### GET USER BY ID
GET http://localhost:3000/api/user/<user_id>
Authorization: Bearer <your_admin_jwt_token>

### update user 

PATCH http://localhost:3000/api/user/<user_id>
Authorization: Bearer <your_admin_jwt_token>
Content-Type: application/json

{
  "name": "Updated Admin Name",
  "location": "Porto, Portugal"
}


### delete user by id
DELETE http://localhost:3000/api/user/<user_id>
Authorization: Bearer <your_admin_jwt_token>
