### Create Sensor
POST http://localhost:3000/api/sensors
Authorization: Bearer <your_jwt_token_here>
Content-Type: application/json

{
  "type": "temperature",
  "location": "Lisboa",
  "status": "active",
  "update_frequency": "hours"
}
### Get All Sensors
GET http://localhost:3000/api/sensors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2RhODk4NjE5NmNhZGNhNTRiMmJmMSIsImlhdCI6MTc0ODk2MTU3OCwiZXhwIjoxNzUxNTUzNTc4fQ.gYeIhh8f5U8mZ9NLqFiBojo8yj0UehJeycCufHvoOfY

### Get One Sensor by ID
GET http://localhost:3000/api/sensors/<sensor_id_here>
Authorization: Bearer <your_jwt_token_here>

### Update Sensor
PATCH http://localhost:3000/api/sensors/<sensor_id_here>
Authorization: Bearer <your_jwt_token_here>
Content-Type: application/json

{
  "status": "inative",
  "location": "Sala 2"
}

### Delete Sensor
DELETE http://localhost:3000/api/sensors/<sensor_id_here>
Authorization: Bearer <your_jwt_token_here>
